#!/usr/bin/env python3
"""Workspace calibration from a kinesthetic (hand-guided) sweep.

Flow (real robot):
    1. Start the bridge:  ./cpp/build/franka_bridge <robot-ip>
       (while waiting for the first command it already publishes state at ~10 Hz)
    2. Put the robot in guiding mode (FR3 wrist buttons / Desk hand-guiding).
    3. Run:  python scripts/calibrate_workspace.py --duration 60
    4. Sweep the EE through every region teleop should reach
       (including below-base heights for pressing/dragging tasks).
    5. Review the printed box; re-run with --write to save it as
       configs/workspace_calibrated.yaml, which overrides teleop.yaml at load
       time (teleop.yaml itself is left untouched; delete the file to revert).

Ctrl+C finishes early and still prints the result.
"""
import argparse
import pathlib
import socket
import struct
import sys
import time

import numpy as np
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from dsfranka.real.franka_client import MAGIC, STATE_FMT


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--state-port", type=int, default=5556)
    ap.add_argument("--duration", type=float, default=60.0, help="sweep time [s]")
    ap.add_argument("--margin", type=float, default=0.02,
                    help="box padding beyond the sweep extremes [m]")
    ap.add_argument("--write", action="store_true",
                    help="save result to configs/workspace_calibrated.yaml")
    ap.add_argument("--out", default=str(ROOT / "configs" / "workspace_calibrated.yaml"))
    args = ap.parse_args()

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("0.0.0.0", args.state_port))
    sock.settimeout(0.5)
    size = struct.calcsize(STATE_FMT)

    print(f"listening for bridge state on :{args.state_port} — sweep the EE now "
          f"({args.duration:.0f} s, Ctrl+C to finish early)")
    pts = []
    t0 = time.time()
    try:
        while time.time() - t0 < args.duration:
            try:
                data, _ = sock.recvfrom(4096)
            except socket.timeout:
                if not pts and time.time() - t0 > 5:
                    print("  (no state packets yet — is franka_bridge running?)")
                continue
            if len(data) != size:
                continue
            vals = struct.unpack(STATE_FMT, data)
            if vals[0] != MAGIC:
                continue
            pts.append(vals[16:19])  # ee_pos (after magic, seq, q[7], dq[7])
            if len(pts) % 100 == 1:
                p = pts[-1]
                print(f"\r  samples={len(pts)}  ee=({p[0]:+.3f}, {p[1]:+.3f}, {p[2]:+.3f})",
                      end="", flush=True)
    except KeyboardInterrupt:
        pass
    print()

    if len(pts) < 10:
        print(f"only {len(pts)} samples — not enough to calibrate. Aborting.")
        sys.exit(1)

    p = np.asarray(pts)
    lo = p.min(axis=0) - args.margin
    hi = p.max(axis=0) + args.margin
    ws = {a: [round(float(lo[i]), 3), round(float(hi[i]), 3)] for i, a in enumerate("xyz")}

    print(f"\n{len(p)} samples over {time.time()-t0:.0f} s, margin ±{args.margin} m:")
    print(yaml.safe_dump({"workspace": ws}, default_flow_style=None, sort_keys=False))
    if args.write:
        with open(args.out, "w") as f:
            f.write("# generated by scripts/calibrate_workspace.py — overrides the\n"
                    "# workspace box in teleop.yaml at load time. Delete to revert.\n")
            yaml.safe_dump({"workspace": ws}, f, default_flow_style=None, sort_keys=False)
        print(f"written -> {args.out}")
    else:
        print("(dry run — re-run with --write to apply)")


if __name__ == "__main__":
    main()
